Repository Azure/Azure-Verified-Modules, pull requests merged in 2023-11, with the labels that each got.

#250 Index updates & adding question/feedback issue to project board
  .github/ISSUE_TEMPLATE/question_feedback.yml
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#251 Added additional possible properties to CMK implementation
  docs/static/includes/interfaces/int.cmk.udt.schema.bicep
Labels: Type: Documentation :page_facing_up:

#252 correcting AVM triage process bug
  .github/policies/eventResponder.yml
  docs/content/help-support/issue-triage/avm-issue-triage.md
Labels: Needs: Triage :mag:

#257 Update TerraformResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#260 Fix: Typo preventing site build
  .github/linters/mlc_config.json
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/content/faq/_index.md
  docs/content/help-support/issue-triage/avm-issue-triage.md
Labels: Needs: Triage :mag:

#262 Add Website Contrib Guide
  docs/content/contributing/website/_index.md
Labels: Type: Documentation :page_facing_up:

#263 Bicep naming convention updates
  .github/ISSUE_TEMPLATE/module_proposal.yml
  .github/ISSUE_TEMPLATE/orphaned_module.yml
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/content/contributing/terraform/_index.md
  docs/content/faq/_index.md
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/specs/bicep/_index.md
  docs/content/specs/shared/_index.md
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
  docs/static/includes/msg-final-conf-new-orph-mod-owners.md
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#268 Adding Contribution Diagrams for bicep contribution guide
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#269 fix: Removed rundant `null` allowed value from nullable UDT properties
  docs/static/includes/interfaces/int.diag.udt.schema.bicep
  docs/static/includes/interfaces/int.rbac.udt.schema.bicep
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#270 updated 1es link
  docs/content/contributing/terraform/_index.md
Labels: Needs: Triage :mag:

#277 Pmeshram/feat/updates- TF specs update showing Note on review from TF PG/Engineering
  docs/content/specs/terraform/_index.md
Labels: Type: Documentation :page_facing_up:, Language: Terraform :globe_with_meridians:

#283 Prjelesi/new module request
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#286 bicep index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#289 fix: Removed excess `s` from MI UDT definition
  docs/static/includes/interfaces/int.mi.udt.schema.bicep
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#284 fix: Updated PE schema to latest module version
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
Labels: Type: Documentation :page_facing_up:

#287 add module statistics to indexes
  docs/content/indexes/_index.md
  docs/content/indexes/bicep/_index.md
  docs/content/indexes/bicep/bicep-pattern-modules.md
  docs/content/indexes/bicep/bicep-resource-modules.md
  docs/content/indexes/terraform/_index.md
  docs/content/indexes/terraform/tf-pattern-modules.md
  docs/content/indexes/terraform/tf-resource-modules.md
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/layouts/shortcodes/moduleNameTelemetryGHTeams.html
  docs/layouts/shortcodes/moduleStats.html
Labels: Type: Documentation :page_facing_up:

#301 Bicep resource module index update & AZD label
  docs/static/governance/avm-standard-github-labels.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#304 chore: include existing repo advice in q and a section
  docs/content/contributing/q-and-a.md
Labels: Needs: Triage :mag:

#305 Fix casing of Azure in module names and update module ownership
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#309 Update to geekdocs v0.44.0 and hugo 0.120.4
  .github/workflows/hugo-build-pr-check.yml
  .github/workflows/hugo-site-build.yml
  docs/themes/hugo-geekdoc/.lycheeignore
  docs/themes/hugo-geekdoc/README.md
  docs/themes/hugo-geekdoc/VERSION
  docs/themes/hugo-geekdoc/data/assets.json
  docs/themes/hugo-geekdoc/i18n/am.yaml
  docs/themes/hugo-geekdoc/layouts/_default/_markup/render-heading.html
  docs/themes/hugo-geekdoc/layouts/_default/baseof.html
  docs/themes/hugo-geekdoc/layouts/partials/menu-bundle-np.html
  docs/themes/hugo-geekdoc/layouts/partials/menu-filetree-np.html
  docs/themes/hugo-geekdoc/layouts/partials/page-header.html
  docs/themes/hugo-geekdoc/layouts/partials/site-footer.html
  docs/themes/hugo-geekdoc/layouts/shortcodes/expand.html
  docs/themes/hugo-geekdoc/layouts/shortcodes/propertylist.html
  docs/themes/hugo-geekdoc/static/fonts/GeekdocIcons.woff
  docs/themes/hugo-geekdoc/static/fonts/GeekdocIcons.woff2
  docs/themes/hugo-geekdoc/static/js/111-7a946536.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/116-831698f6.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/127-50679170.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/189-239ec1e3.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/244-58363060.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/254-c6d47b41.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/27-f65feaa5.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/284-3123c5bb.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/351-71958ace.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/360-7b298c8d.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/365-eb6645ca.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/371-301734d9.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/407-73d671b2.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/46-8ae016ba.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/469-5c6960d1.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/506-2d1f47d3.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/555-6ea47e9d.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/601-0a3e0cc6.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/637-e93ad57f.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/637-e93ad57f.chunk.min.js.LICENSE.txt
  docs/themes/hugo-geekdoc/static/js/653-a11b871f.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/687-be7491b1.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/688-e8e1f365.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/690-4454267b.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/707-2b750270.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/715-6a27583b.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/740-374cadec.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/762-fa9a1179.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/771-942a62df.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/807-54a776b6.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/807-54a776b6.chunk.min.js.LICENSE.txt
  docs/themes/hugo-geekdoc/static/js/816-2507a6de.chunk.min.js
  docs/themes/hugo-geekdoc/static/js/katex-373b7f53.bundle.min.js
  docs/themes/hugo-geekdoc/static/js/main-924a1933.bundle.min.js
  docs/themes/hugo-geekdoc/static/js/main-924a1933.bundle.min.js.LICENSE.txt
  docs/themes/hugo-geekdoc/static/js/mermaid-a27d7d20.bundle.min.js
  docs/themes/hugo-geekdoc/static/js/search-9719be99.bundle.min.js
  docs/themes/hugo-geekdoc/static/js/search-9719be99.bundle.min.js.LICENSE.txt
  docs/themes/hugo-geekdoc/static/katex-1799419e.min.css
  docs/themes/hugo-geekdoc/static/main-23bdf5c0.min.css
  docs/themes/hugo-geekdoc/theme.toml
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:, Type: Hygiene :broom:

#310 Prjelesi/update index
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#318 Update to Bicep Contribution Guide & Tooling
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/content/contributing/bicep/prerequisites.md
Labels: Needs: Triage :mag:

#320 bicep resource module index updated
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#323 feat: Updated Bicep schema to support additional ID cases
  docs/static/includes/interfaces/int.rbac.input.bicep
  docs/static/includes/interfaces/int.rbac.udt.schema.bicep
Labels: Type: Documentation :page_facing_up:

#321 Triage process updates
  .github/ISSUE_TEMPLATE/module_proposal.yml
  .github/ISSUE_TEMPLATE/orphaned_module.yml
  .github/policies/eventResponder.yml
  .github/policies/scheduledSearches.yml
  docs/content/contributing/q-and-a.md
  docs/content/faq/_index.md
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/help-support/issue-triage/issue-triage-automation.md
  docs/content/specs/bicep/_index.md
  docs/content/specs/shared/_index.md
Labels: Type: Documentation :page_facing_up:

#317 Merge tfvm codex resource rules into avm tf spec
  docs/content/specs/terraform/_index.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:, Language: Terraform :globe_with_meridians:

#330 Update TerraformResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#329 Update TerraformPatternModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
Labels: Needs: Triage :mag:

#331 Update TerraformResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#346 Pmeshram/feat/updates
  docs/static/module-indexes/TerraformPatternModules.csv
Labels: Needs: Triage :mag:

#350 Bicep resource index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#345 Fixing description for `diag-UDT` in Interface specs
  docs/static/includes/interfaces/int.diag.udt.schema.bicep
Labels: Needs: Triage :mag:

#351 Bicep resource modules index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#354 fix: interface for tf pe (missing tags)
  docs/static/includes/interfaces/int.pe.schema.tf
Labels: Needs: Triage :mag:

#356 feat: Updated interface usage as per agreed upon PE updates
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:
