Repository Azure/Azure-Verified-Modules, pull requests merged in 2023-09, with the labels that each got.

#37 Add Update Only Feature to GitHub Labels Script
  docs/content/specs/shared/_index.md
  docs/static/scripts/Set-AvmGitHubLabels.ps1
Labels: Type: Feature Request :heavy_plus_sign:

#47 Fixed wording
  docs/content/specs/shared/_index.md
Labels: Type: Documentation :page_facing_up:

#48 Users/alsehr/diagnostic changes
  docs/static/includes/interfaces/int.diag.input.bicep
  docs/static/includes/interfaces/int.diag.input.tf
  docs/static/includes/interfaces/int.diag.schema.bicep.json
  docs/static/includes/interfaces/int.diag.schema.tf.json
Labels: Type: Documentation :page_facing_up:

#51 Initialize Module Indexes ((Catalog) AB#29902
  docs/content/indexes/_index.md
  docs/content/indexes/bicep/_index.md
  docs/content/indexes/bicep/bicep-pattern-modules.md
  docs/content/indexes/bicep/bicep-resource-modules.md
  docs/content/indexes/terraform/_index.md
  docs/content/indexes/terraform/tf-pattern-modules.md
  docs/content/indexes/terraform/tf-resource-modules.md
  docs/content/specs/shared/_index.md
  docs/data/menu/main.yaml
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/layouts/shortcodes/moduleNameTelemetryGHTeams.html
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#54 Add new FAQ for LZAs and New RMFR for Module Outputs
  docs/content/faq/_index.md
  docs/content/specs/shared/_index.md
Labels: Type: Documentation :page_facing_up:

#60 [Wiki] Added missing `service` to PE interface
  docs/static/includes/interfaces/int.pe.input.bicep
  docs/static/includes/interfaces/int.pe.input.tf
  docs/static/includes/interfaces/int.pe.schema.bicep.json
  docs/static/includes/interfaces/int.pe.schema.tf
Labels: Type: Documentation :page_facing_up:

#69 RP Collaboration: internal wiki URL added
  docs/content/specs/shared/_index.md
Labels: Type: Documentation :page_facing_up:

#70 Add nullable = false to prevent precondition to fail
  docs/static/includes/interfaces/int.diag.schema.tf
Labels: Type: Bug :bug:, Type: Documentation :page_facing_up:, Language: Terraform :globe_with_meridians:

#72 Made UserAssignedIdentities optional in CMK schema
  docs/static/includes/interfaces/int.cmk.schema.tf
Labels: Type: Documentation :page_facing_up:

#80 Updated PE schema to account for lock & role assignment schema
  docs/content/specs/shared/interfaces.md
  docs/static/includes/interfaces/int.pe.udt.schema.bicep
Labels: Type: Documentation :page_facing_up:

#94 Added missing `.` at the end of parameter description
  docs/static/includes/interfaces/int.mi.udt.schema.bicep
Labels: Type: Documentation :page_facing_up:

#95 Add apiSpecsList Update Workflow
  .github/workflows/platform.apiSpecs.yml
  utilities/pipelines/sharedScripts/Set-EnvironmentOnAgent.ps1
  utilities/tools/platform/Set-ApiSpecsFile.ps1
Labels: Type: Hygiene :broom:

#98 Update Repo Default Files
  README.md
  SECURITY.md
  SUPPORT.md
  docs/content/help-support/_index.md
  docs/data/menu/main.yaml
Labels: Type: Documentation :page_facing_up:

#99 Updated the comment next to the telemetry module version var
  docs/static/includes/sample.telem.bicep
Labels: Type: Documentation :page_facing_up:

#100 Added ask to add 'Required if (...).' sentence for conditional parameter descriptions
  docs/content/specs/bicep/_index.md
Labels: Type: Documentation :page_facing_up:

#101 Usage examples proposal
  docs/content/specs/bicep/_index.md
Labels: Type: Documentation :page_facing_up:

#102 Updated parameter examples specs
  docs/content/specs/bicep/_index.md
Labels: Type: Documentation :page_facing_up:

#103 Fixed PE interface telemetry usage
  docs/static/includes/interfaces/int.pe.udt.schema.bicep
Labels: Type: Documentation :page_facing_up:

#117 Updated resource deployment code for the Private Endpoint extension resource
  docs/content/specs/shared/interfaces.md
  docs/layouts/shortcodes/expand.html
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#125 Fixed link to diagnostic dependencies file
  docs/content/contributing/bicep/_index.md
Labels: Type: Documentation :page_facing_up:

#126 Updated tags interface
  docs/static/includes/interfaces/int.tags.udt.schema.bicep
Labels: Type: Documentation :page_facing_up:

#124 updated logic for Terraform module indexes
  docs/content/indexes/bicep/bicep-pattern-modules.md
  docs/content/indexes/bicep/bicep-resource-modules.md
  docs/content/indexes/terraform/tf-pattern-modules.md
  docs/content/indexes/terraform/tf-resource-modules.md
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/layouts/shortcodes/moduleNameTelemetryGHTeams.html
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:, Type: Feature Request :heavy_plus_sign:

#132 Various Doc Enhancements
  docs/content/contributing/process.md
  docs/content/contributing/q-and-a.md
  docs/content/contributing/terraform/_index.md
  docs/content/faq/_index.md
  docs/content/help-support/_index.md
  docs/content/specs/shared/_index.md
Labels: Type: Documentation :page_facing_up:

#134 Update PE to latest appreviation
  docs/static/includes/interfaces/int.pe.schema.tf
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
Labels: Type: Documentation :page_facing_up:

#135 Added 2 more specs regard the Bicep test files
  docs/content/specs/bicep/_index.md
Labels: Needs: Triage :mag:

#140 Update RMFR4 with resource dependency clarity
  docs/content/specs/shared/_index.md
Labels: Type: Documentation :page_facing_up:
