Repository Azure/Azure-Verified-Modules, pull requests merged in 2023-12, with the labels that each got.

#361 Bicep resource module index update
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#362 Documentation and module triage updates
  .github/ISSUE_TEMPLATE/module_proposal.yml
  .github/ISSUE_TEMPLATE/orphaned_module.yml
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/specs/shared/_index.md
  docs/static/includes/msg-final-conf-new-orph-mod-owners.md
  docs/static/includes/msg-final-conf-new-prop-mod-owners.md
  docs/static/includes/msg-std-reply-new-orph-mod-owners.md
  docs/static/includes/msg-std-reply-new-prop-mod-owners.md
Labels: Type: Documentation :page_facing_up:

#365 index updates
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#368 bicep resource index update
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#369 Pmeshram/feat/updates
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#371 update favicon to AVM logo
  docs/themes/hugo-geekdoc/static/brand.svg
  docs/themes/hugo-geekdoc/static/favicon/android-chrome-144x144.png
  docs/themes/hugo-geekdoc/static/favicon/android-chrome-192x192.png
  docs/themes/hugo-geekdoc/static/favicon/android-chrome-256x256.png
  docs/themes/hugo-geekdoc/static/favicon/android-chrome-36x36.png
  docs/themes/hugo-geekdoc/static/favicon/android-chrome-384x384.png
  docs/themes/hugo-geekdoc/static/favicon/android-chrome-48x48.png
  docs/themes/hugo-geekdoc/static/favicon/android-chrome-512x512.png
  docs/themes/hugo-geekdoc/static/favicon/android-chrome-72x72.png
  docs/themes/hugo-geekdoc/static/favicon/android-chrome-96x96.png
  docs/themes/hugo-geekdoc/static/favicon/favicon-16x16.png
  docs/themes/hugo-geekdoc/static/favicon/favicon-32x32.png
  docs/themes/hugo-geekdoc/static/favicon/favicon-48x48.png
  docs/themes/hugo-geekdoc/static/favicon/favicon.ico
  docs/themes/hugo-geekdoc/static/favicon/favicon.svg
  docs/themes/hugo-geekdoc/static/favicon/mstile-144x144.png
  docs/themes/hugo-geekdoc/static/favicon/mstile-150x150.png
  docs/themes/hugo-geekdoc/static/favicon/mstile-310x150.png
  docs/themes/hugo-geekdoc/static/favicon/mstile-310x310.png
  docs/themes/hugo-geekdoc/static/favicon/mstile-70x70.png
Labels: Type: Documentation :page_facing_up:

#355 Adding Workflow for GitHub Team Linting
  .github/workflows/github-teams-check-existance.yml
  utilities/pipelines/sharedScripts/teamLinter/Find-GitHubIssue.ps1
  utilities/pipelines/sharedScripts/teamLinter/Get-AvmCsv.ps1
  utilities/pipelines/sharedScripts/teamLinter/Get-AvmGitHubTeamRepoConfiguration.ps1
  utilities/pipelines/sharedScripts/teamLinter/Get-AvmGitHubTeamsData.ps1
  utilities/pipelines/sharedScripts/teamLinter/Invoke-AvmGitHubTeamLinter.ps1
  utilities/pipelines/sharedScripts/teamLinter/New-AvmGitHubTeamsIssue.ps1
  utilities/pipelines/sharedScripts/teamLinter/Set-AvmGitHubTeamsIssue.ps1
Labels: Needs: Triage :mag:

#312 feat: Added explicit reference to telemetry opt-out as discussed
  docs/content/specs/shared/_index.md
  docs/static/includes/telemetry-information-notice.md
  docs/static/includes/telemetry-information-notice.txt
Labels: Type: Documentation :page_facing_up:

#378 TF pattern module index updates
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#380 [bug]: Adding Publishing Logic to determine branch
  .github/workflows/github-teams-check-existance.yml
Labels: Needs: Triage :mag:

#404 Bicep resource module index update
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#405 fixes: Added missing `.` at the end of the `conditions` parameter's description
  docs/static/includes/interfaces/int.rbac.udt.schema.bicep
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#412 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#414 Bicep resource module index update
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#370 fix GH policy service bug; add saved issue queries; clarify non-FTE permissions in SNFR20
  .github/policies/eventResponder.yml
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/specs/shared/_index.md
Labels: Type: Documentation :page_facing_up:

#419 Bicep resource module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#420 Bicep resource module index update
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#430 TF resource module index updates
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#434 Bicep resource modules index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#435 [AVM] [FAQ] Updated images to align with the latest module names
  docs/static/img/faq/use-bicep-module-01.png
  docs/static/img/faq/use-bicep-module-02.png
  docs/static/img/faq/use-bicep-module-03.png
  docs/static/img/faq/use-bicep-module-04.png
  docs/static/img/faq/use-bicep-module-05.png
  docs/static/img/faq/use-bicep-module-06.png
Labels: Needs: Triage :mag:

#441 Update TerraformResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#439 correct typo in system assigned principal output
  docs/content/specs/shared/_index.md
Labels: Type: Documentation :page_facing_up:

#447 Bicep and TF resource module index updates
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#403 feat: Added Module Feature Table automation
  .github/workflows/code-review.yml
  .github/workflows/platform.updateModuleRegistryTables.yml
  docs/content/indexes/bicep/_index.md
  docs/content/specs/shared/_index.md
  docs/static/includes/module-features/bicepBadges.md
  docs/static/includes/module-features/bicepFeatures.csv
  docs/static/includes/telemetry-information-notice.md
  utilities/tools/platform/Set-BicepModuleStatusBadgesTable.ps1
  utilities/tools/platform/Set-BicepModulesFeatureCSV.ps1
  utilities/tools/platform/helper/Get-ModulesFeatureOutline.ps1
  utilities/tools/platform/helper/Get-PipelineFileName.ps1
  utilities/tools/platform/helper/Get-PipelineNameFromFile.ps1
  utilities/tools/platform/helper/Get-PipelineStatusUrl.ps1
Labels: Type: Documentation :page_facing_up:

#448 Updated invalid actual regex to GitHub action version of regex
  .github/workflows/code-review.yml
Labels: Type: Bug :bug:, Type: AVM :a: :v: :m:

#467 Bicep resource module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#446 Csidebotham/teamlinter/patch 01
  utilities/pipelines/sharedScripts/teamLinter/Invoke-AvmGitHubTeamLinter.ps1
  utilities/pipelines/sharedScripts/teamLinter/New-AvmGitHubTeamsIssue.ps1
  utilities/pipelines/sharedScripts/teamLinter/Set-AvmGitHubTeamsIssue.ps1
Labels: Type: Hygiene :broom:

#450 Added new saved query to AVM triage process
  .github/ISSUE_TEMPLATE/module_proposal.yml
  .github/ISSUE_TEMPLATE/orphaned_module.yml
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/static/includes/msg-final-conf-new-orph-mod-owners.md
  docs/static/includes/msg-final-conf-new-prop-mod-owners.md
  docs/static/includes/msg-std-reply-new-orph-mod-owners.md
  docs/static/includes/msg-std-reply-new-prop-mod-owners.md
Labels: Type: Documentation :page_facing_up:

#473 fix: AVM Team Linter - Follow Feature addition in last PR
  utilities/pipelines/sharedScripts/teamLinter/New-AvmGitHubTeamsIssue.ps1
  utilities/pipelines/sharedScripts/teamLinter/Set-AvmGitHubTeamsIssue.ps1
Labels: Needs: Triage :mag:, Type: Bug :bug:, Needs: Immediate Attention :bangbang:

#478 fix: team-linter issue duplication
  utilities/pipelines/sharedScripts/teamLinter/Find-GitHubIssue.ps1
Labels: Needs: Triage :mag:

#480 Bicep resource module index update
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:
