Repository Azure/Azure-Verified-Modules, pull requests merged in 2023-10, with the labels that each got.

#141 Updated RES modules CSV - removed VWAN & VMSS
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:, Language: Terraform :globe_with_meridians:

#143 Simplified schema for diverse extension resources
  docs/static/includes/interfaces/int.diag.udt.schema.bicep
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
  docs/static/includes/interfaces/int.rbac.udt.schema.bicep
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#158 module index filtering, readability & content updates
  .github/linters/mlc_config.json
  docs/content/indexes/bicep/bicep-pattern-modules.md
  docs/content/indexes/bicep/bicep-resource-modules.md
  docs/content/indexes/terraform/tf-pattern-modules.md
  docs/content/indexes/terraform/tf-resource-modules.md
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/layouts/shortcodes/moduleNameTelemetryGHTeams.html
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#162 timeline and approach for evolving CARML modules to AVM
  docs/content/faq/_index.md
Labels: Type: Documentation :page_facing_up:

#167 CARML to AVM timeline review
  docs/content/faq/_index.md
Labels: Needs: Triage :mag:

#175 updating the Bicep resource module index
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#133 updates for module composition (guidance for not using non-AVM modules) & minor doc updates
  docs/content/contributing/process.md
  docs/content/specs/bicep/_index.md
  docs/content/specs/shared/_index.md
  docs/content/specs/shared/module-classifications.md
  docs/content/specs/terraform/_index.md
Labels: Type: Documentation :page_facing_up:

#179 Module index updates
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#136 Started with CI-setup guide
  docs/content/contributing/bicep/_index.md
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/content/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files.md
  docs/content/contributing/bicep/bicep-contribution-flow/validate-bicep-module-locally.md
  docs/content/contributing/bicep/composition.md
  docs/content/contributing/bicep/prerequisites.md
  docs/content/contributing/process.md
  docs/content/specs/bicep/_index.md
  docs/content/specs/shared/_index.md
  docs/content/specs/shared/interfaces.md
  docs/data/menu/main.yaml
  docs/static/img/bicep-ci/actionsEnable.png
  docs/static/img/bicep-ci/forkSettings.png
  docs/static/img/bicep-ci/forkSettingsSecretAdd.png
  docs/static/img/bicep-ci/forkSettingsSecrets.png
  docs/static/img/bicep-ci/workflow_permissions.png
  docs/static/img/contribution/badgeDropdown.png
  docs/static/img/contribution/pipelineBadge.png
  docs/static/includes/avm.[res-res].template.pattern.yml
Labels: Type: Documentation :page_facing_up:

#183 index update for bicep resource modules
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#180 adding capability to show CSV last updated time
  docs/content/indexes/bicep/bicep-pattern-modules.md
  docs/content/indexes/bicep/bicep-resource-modules.md
  docs/content/indexes/terraform/tf-pattern-modules.md
  docs/content/indexes/terraform/tf-resource-modules.md
  docs/layouts/shortcodes/csvUpdated.html
Labels: Type: Documentation :page_facing_up:

#161 Issue triage process updates
  .github/ISSUE_TEMPLATE/module_proposal.yml
  .github/ISSUE_TEMPLATE/orphaned_module.yml
  .github/ISSUE_TEMPLATE/question_feedback.yml
  .github/policies/eventResponder.yml
  docs/content/concepts/what-why-how.md
  docs/content/contributing/bicep/_index.md
  docs/content/contributing/process.md
  docs/content/faq/_index.md
  docs/content/glossary/_index.md
  docs/content/help-support/issue-triage-automation.md
  docs/content/help-support/issue-triage/_index.md
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/help-support/issue-triage/issue-triage-automation.md
  docs/content/specs/shared/_index.md
  docs/data/menu/main.yaml
  docs/static/governance/avm-standard-github-labels.csv
  docs/static/includes/msg-final-conf-new-orph-mod-owners.md
  docs/static/includes/msg-final-conf-new-prop-mod-owners.md
  docs/static/includes/msg-std-reply-new-orph-mod-owners.md
  docs/static/includes/msg-std-reply-new-prop-mod-owners.md
Labels: Type: Documentation :page_facing_up:

#193 updates to the orphaned module process
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/specs/shared/module-lifecycle.md
  docs/static/includes/orphaned-module-notice.md
Labels: Type: Documentation :page_facing_up:

#194 language fix in orphaned module notice
  docs/static/includes/orphaned-module-notice.md
Labels: Type: Documentation :page_facing_up:

#199 GH Policy Service - fixing language dependent labeling
  .github/ISSUE_TEMPLATE/module_proposal.yml
  .github/ISSUE_TEMPLATE/orphaned_module.yml
  .github/policies/eventResponder.yml
Labels: Type: Documentation :page_facing_up:

#200 key vault, PIP, SSH public key published
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#204 triage process updates
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/specs/shared/_index.md
  docs/content/specs/shared/module-lifecycle.md
  docs/static/includes/msg-final-conf-new-prop-mod-owners.md
Labels: Type: Documentation :page_facing_up:

#209 Bicep index update
  docs/content/indexes/bicep/bicep-pattern-modules.md
  docs/content/indexes/bicep/bicep-resource-modules.md
  docs/content/indexes/terraform/tf-pattern-modules.md
  docs/content/indexes/terraform/tf-resource-modules.md
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#214 faq updates
  docs/content/faq/_index.md
Labels: Type: Documentation :page_facing_up:

#221 updates to Bicep resource module index
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#222 fix status in Bicep resource module index
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#225 FAQ updated with how to use published Bicep modules
  docs/content/faq/_index.md
  docs/static/img/faq/use-bicep-module-01.png
  docs/static/img/faq/use-bicep-module-02.png
  docs/static/img/faq/use-bicep-module-03.png
  docs/static/img/faq/use-bicep-module-04.png
  docs/static/img/faq/use-bicep-module-05.png
  docs/static/img/faq/use-bicep-module-06.png
Labels: Type: Documentation :page_facing_up:

#229 [Wiki] Recovered original Bicep index page
  docs/content/contributing/bicep/_index.md
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#228 AVM preview notice added
  docs/content/contributing/process.md
Labels: Type: Documentation :page_facing_up:

#232 Small fix to PE Variant 2 referenceing incorrect hardcoded value
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
Labels: Needs: Author Feedback :ear:

#227 adding telemetry information notice
  README.md
  docs/content/specs/shared/_index.md
  docs/static/includes/telemetry-information-notice.md
Labels: Type: Documentation :page_facing_up:

#215 triage updates; BRM triage
  .github/ISSUE_TEMPLATE/question_feedback.yml
  .github/policies/eventResponder.yml
  .github/policies/scheduledSearches.yml
  docs/content/help-support/_index.md
  docs/content/help-support/issue-triage/_index.md
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/help-support/issue-triage/brm-issue-triage.md
  docs/content/help-support/issue-triage/issue-triage-automation.md
  docs/content/specs/shared/module-lifecycle.md
  docs/data/menu/main.yaml
  docs/static/governance/avm-standard-github-labels.csv
Labels: Type: Documentation :page_facing_up:

#239 Bicep resource modules index update
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#240 Bicep resource module index update
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#242 Prjelesi/tf triage update
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#235 minor update on the issue message template
  docs/static/includes/msg-final-conf-new-prop-mod-owners.md
  docs/static/includes/msg-std-reply-new-orph-mod-owners.md
  docs/static/includes/msg-std-reply-new-prop-mod-owners.md
Labels: Type: Documentation :page_facing_up:

#246 updating Bicep resource module index
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#245 Adding note about diagnostic usage with incompatible resources
  docs/content/specs/shared/interfaces.md
Labels: Type: Documentation :page_facing_up:

#247 Adding questions from CSU AVM day to FAQ
  docs/content/faq/_index.md
Labels: Type: Documentation :page_facing_up:
