Repository Azure/Azure-Verified-Modules, pull requests merged in 2024-11, with the labels that each got.

#1652 feat: [feat/doc-updates] open external links in new tab/window
  docs/layouts/_default/_markup/render-link.html
  docs/static/includes/module-features/bicepFeatures.csv
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#1703 favicon fix
  docs/themes/hugo-geekdoc/static/favicon/favicon-16x16.png
  docs/themes/hugo-geekdoc/static/favicon/favicon-32x32.png
  docs/themes/hugo-geekdoc/static/favicon/favicon-48x48.png
  docs/themes/hugo-geekdoc/static/favicon/favicon.ico
  docs/themes/hugo-geekdoc/static/favicon/favicon.svg
Labels: Type: Documentation :page_facing_up:

#1704 introducing AlternativeNames
  docs/layouts/shortcodes/moduleHistory.html
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/layouts/shortcodes/moduleNameTelemetryGHTeams.html
  docs/layouts/shortcodes/moduleStats.html
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/BicepUtilityModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
  docs/static/module-indexes/TerraformUtilityModules.csv
Labels: Type: Documentation :page_facing_up:

#1707 avm-tf-module-index-update
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1708 [feat/doc-updates] main-sync
  docs/content/usage/_index.md
  docs/content/usage/quickstart/_index.md
  docs/layouts/shortcodes/moduleHistory.html
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/layouts/shortcodes/moduleNameTelemetryGHTeams.html
  docs/layouts/shortcodes/moduleStats.html
  docs/static/governance/apiSpecsList.json
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/BicepUtilityModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
  docs/static/module-indexes/TerraformUtilityModules.csv
  docs/themes/hugo-geekdoc/static/favicon/favicon-16x16.png
  docs/themes/hugo-geekdoc/static/favicon/favicon-32x32.png
  docs/themes/hugo-geekdoc/static/favicon/favicon-48x48.png
  docs/themes/hugo-geekdoc/static/favicon/favicon.ico
  docs/themes/hugo-geekdoc/static/favicon/favicon.svg
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1720 chore: update composition to allow any folder name for default example
  docs/content/contributing/terraform/composition.md
Labels: Needs: Triage :mag:

#1555 tfnfr36 code sample add
  docs/content/specs-defs/specs/terraform/_index.md
Labels: Needs: Triage :mag:

#1722 amend missing content
  docs/content/specs-defs/includes/terraform/shared/non-functional/TFNFR29.md
  docs/content/specs-defs/includes/terraform/shared/non-functional/TFNFR32.md
  docs/content/specs-defs/includes/terraform/shared/non-functional/TFNFR34.md
Labels: Needs: Triage :mag:

#1724 Added TF resource module In the index -
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1728 Updated the new module owner for avm-res-compute-gallery
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1736 Bicep and Terraform module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:
