Repository Azure/Azure-Verified-Modules, pull requests merged in 2024-07, with the labels that each got.

#1160 Bicep module index updates
  .github/ISSUE_TEMPLATE/module_proposal.yml
  .github/ISSUE_TEMPLATE/orphaned_module.yml
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#1161 avm-tf-module-index-update
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1166 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#1163 index update
  docs/static/module-indexes/TerraformPatternModules.csv
Labels: Needs: Triage :mag:

#1175 Fix: corrected a small typo
  docs/content/indexes/bicep/_index.md
Labels: Needs: Triage :mag:

#1182 Fix Bicep Module Latest Version Display Ordering
  .github/workflows/hugo-build-pr-check.yml
  .github/workflows/hugo-site-build.yml
  docs/layouts/shortcodes/moduleNameStatusOwners.html
Labels: Needs: Triage :mag:

#1197 AVM module index update
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Needs: Triage :mag:

#1198 docs: Update to placeholder values
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1168 index update
  docs/static/module-indexes/TerraformPatternModules.csv
Labels: Type: Hygiene :broom:

#1211 TF index update july-2
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1238 index update
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1239 Update TerraformResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1247 feat: Updated RBAC schema for Bicep to latest agreed-upon proposal
  docs/static/includes/interfaces/int.rbac.input.bicep
  docs/static/includes/interfaces/int.rbac.udt.schema.bicep
Labels: Type: Documentation :page_facing_up:

#1248 fix: Updated spec following a suggested simplification
  docs/static/includes/interfaces/int.rbac.input.bicep
  docs/static/includes/interfaces/int.rbac.udt.schema.bicep
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1249 feat: Updated schema to latest PE module interface
  docs/static/includes/interfaces/int.pe.input.bicep
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
Labels: Type: Documentation :page_facing_up:
