Repository Azure/Azure-Verified-Modules, pull requests merged in 2024-04, with the labels that each got.

#805 feat: Added implementation details for the `zone` & `zones` parameter's
  docs/content/specs/bicep/_index.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#713 feat: Added documentation for Bicep post-deployment tests
  docs/content/specs/bicep/_index.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#809 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#813 fix: Small update to AZ proposal to account for unexpected Bicep issue
  docs/content/specs/bicep/_index.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#812 Pmeshram/feat/updates
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#808 update AVM site menu
  docs/content/contributing/bicep/_index.md
  docs/content/contributing/terraform/_index.md
  docs/content/help-support/GH-links.md
  docs/content/help-support/issue-triage/_index.md
  docs/content/indexes/bicep/_index.md
  docs/content/indexes/terraform/_index.md
  docs/content/specs/module-specs.md
  docs/data/menu/main.yaml
Labels: Type: Documentation :page_facing_up:

#786 issue template improvements
  .github/ISSUE_TEMPLATE/config.yml
Labels: Type: Hygiene :broom:

#818 Update int.tags.schema.tf
  docs/static/includes/interfaces/int.tags.schema.tf
Labels: Needs: Triage :mag:

#787 feat: Added the ability to specify a custom resource group when deploying a private endpoint
  docs/static/includes/interfaces/int.pe.input.bicep
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
Labels: Type: Documentation :page_facing_up:

#819 customer presentation updates
  docs/content/resources/AVM-Overview-Customer-presentation.pdf
Labels: Type: Documentation :page_facing_up:

#826 fix: Fixed incorrect PE schema, not utilizing correct property
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
Labels: Needs: Triage :mag:, Type: Bug :bug:

#827 fix: Fixed a typo in PE schema, improving the "search/replace" friendliness
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
Labels: Needs: Triage :mag:

#820 index files updated
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#834 fix: updating examples for enable/disable bicep workflows
  docs/content/contributing/bicep/bicep-contribution-flow/enable-or-disable-workflows.md
Labels: Needs: Triage :mag:

#836 Pmeshram/feat/updates
  docs/content/community/_index.md
Labels: Needs: Triage :mag:

#838 Pmeshram/feat/updates
  docs/content/community/_index.md
Labels: Needs: Triage :mag:

#839 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#803 feat: Added a spec to describe the type casting we recommend to do on behalf of the user
  docs/content/specs/bicep/_index.md
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#817 fix: Applied suggestion to simplify zones
  docs/content/specs/bicep/_index.md
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#840 fix: Update module workflow template
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/static/includes/avm.[res-ptn].workflow.template.yml
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#844 Feat/matebarabas/index-updates
  docs/content/help-support/module-support.md
  docs/content/resources/AVM-Overview-Customer-presentation.pdf
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#816 Feat: Update the Team Linter permissions test structure
  utilities/pipelines/sharedScripts/teamLinter/Find-AvmGitHubTeamOwner.ps1
  utilities/pipelines/sharedScripts/teamLinter/Invoke-AvmGitHubTeamLinter.ps1
  utilities/pipelines/sharedScripts/teamLinter/Test-AvmGitHubTeamPermission.ps1
Labels: Needs: Triage :mag:

#828 fix: Added missing UDT parameter for Bicep PE
  docs/static/includes/interfaces/int.pe.input.bicep
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
Labels: Needs: Triage :mag:, Type: Bug :bug:, Type: Documentation :page_facing_up:

#855 index update
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#858 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#865 feat: add principal_type to role_assignments interface
  docs/static/includes/interfaces/int.rbac.schema.tf
Labels: Needs: Triage :mag:

#860 Pmeshram/feat/updates
  docs/content/_index.md
  docs/content/community/_index.md
  docs/content/resources/community/_index.md
  docs/data/menu/main.yaml
Labels: Type: Documentation :page_facing_up:

#852 fix: Update AVM spec `Expected Test Directories` to be applicable for res modules only
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/content/specs/bicep/_index.md
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:, Class: Resource Module :package:

#857 Add module versions to indexes
  .github/workflows/hugo-site-build.yml
  docs/config.toml
  docs/layouts/shortcodes/expand.html
  docs/layouts/shortcodes/moduleHistory.html
  docs/layouts/shortcodes/moduleNameStatusOwners.html
Labels: Type: Documentation :page_facing_up:, Type: Feature Request :heavy_plus_sign:

#866 module index updates
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#867 update resources page
  docs/content/resources/_index.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#868 fixing errors in new module index version feature
  docs/config.toml
  docs/layouts/shortcodes/moduleHistory.html
  docs/layouts/shortcodes/moduleNameStatusOwners.html
Labels: Type: Documentation :page_facing_up:

#795 Docs/telemetry
  docs/content/specs/bicep/_index.md
  docs/content/specs/shared/_index.md
Labels: Type: Documentation :page_facing_up:

#869 fixing expand/collapse mechanism in navigation
  docs/content/specs-defs/_index.md
  docs/content/specs-defs/module-classifications.md
  docs/content/specs-defs/module-lifecycle.md
  docs/content/specs-defs/specs/_index.md
  docs/content/specs-defs/specs/bicep/_index.md
  docs/content/specs-defs/specs/shared/_index.md
  docs/content/specs-defs/specs/shared/interfaces.md
  docs/content/specs-defs/specs/terraform/_index.md
  docs/content/specs-defs/team-definitions.md
  docs/data/menu/main.yaml
Labels: Type: Documentation :page_facing_up:

#871 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#870 Feat/matebarabas/site-updates
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/content/contributing/bicep/bicep-contribution-flow/owner-contribution-flow.md
  docs/content/contributing/bicep/composition.md
  docs/content/contributing/process.md
  docs/content/contributing/terraform/composition.md
  docs/content/contributing/terraform/terraform-contribution-flow/_index.md
  docs/content/contributing/terraform/terraform-contribution-flow/owner-contribution-flow.md
  docs/content/faq/_index.md
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/indexes/bicep/_index.md
Labels: Type: Documentation :page_facing_up:

#873 Fix missing hyphen in Test-AvmGitHubTeamPermission function call
  utilities/pipelines/sharedScripts/teamLinter/Invoke-AvmGitHubTeamLinter.ps1
Labels: Needs: Triage :mag:

#876 Bicep index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#879 feat: Updated Bicep feature table to include CMK & Indentity instead of Public IP
  docs/static/includes/module-features/bicepFeatures.csv
  utilities/tools/platform/Set-BicepModulesFeatureCSV.ps1
  utilities/tools/platform/helper/Get-ModulesFeatureOutline.ps1
Labels: Type: Documentation :page_facing_up:

#886 Bug fix in perm check
  utilities/pipelines/sharedScripts/teamLinter/Invoke-AvmGitHubTeamLinter.ps1
Labels: Needs: Triage :mag:

#888 Bicep module index updates
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/content/contributing/bicep/prerequisites.md
  docs/content/contributing/q-and-a.md
  docs/content/contributing/terraform/terraform-contribution-flow/_index.md
  docs/content/faq/_index.md
  docs/content/glossary/_index.md
  docs/content/help-support/telemetry.md
  docs/content/specs-defs/module-classifications.md
  docs/content/specs-defs/specs/bicep/_index.md
  docs/content/specs-defs/specs/shared/_index.md
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#899 Module Index Update
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#916 Pmeshram/feat/updates
  docs/static/module-indexes/TerraformPatternModules.csv
Labels: Needs: Triage :mag:

#919 module index updates
  docs/content/contributing/bicep/bicep-contribution-flow/enable-or-disable-workflows.md
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#880 post migration index page updates
  docs/content/faq/_index.md
  docs/content/indexes/bicep/_index.md
  docs/content/indexes/bicep/bicep-pattern-modules.md
  docs/content/indexes/bicep/bicep-resource-modules.md
  docs/content/indexes/terraform/_index.md
  docs/content/indexes/terraform/tf-pattern-modules.md
  docs/content/indexes/terraform/tf-resource-modules.md
  docs/layouts/shortcodes/moduleHistory.html
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/layouts/shortcodes/moduleStats.html
Labels: Type: Documentation :page_facing_up:
