Repository Azure/Azure-Verified-Modules, pull requests merged in 2024-05, with the labels that each got.

#925 Bicep module index update
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#921 Add known issues page and update SNFR2
  docs/content/help-support/known-issues.md
  docs/content/specs-defs/specs/shared/_index.md
  docs/data/menu/main.yaml
Labels: Type: Documentation :page_facing_up:, Type: Feature Request :heavy_plus_sign:

#922 updating language related to CARML/TFVM migration
  .github/ISSUE_TEMPLATE/module_proposal.yml
  docs/content/_index.md
  docs/content/contributing/bicep/_index.md
  docs/content/contributing/q-and-a.md
  docs/content/contributing/terraform/_index.md
  docs/content/faq/_index.md
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/help-support/issue-triage/brm-issue-triage.md
  docs/content/indexes/bicep/bicep-pattern-modules.md
  docs/content/indexes/bicep/bicep-resource-modules.md
  docs/content/indexes/terraform/tf-pattern-modules.md
  docs/content/indexes/terraform/tf-resource-modules.md
  docs/content/specs-defs/module-lifecycle.md
  docs/content/specs-defs/specs/bicep/_index.md
  docs/static/governance/avm-standard-github-labels.csv
Labels: Type: Documentation :page_facing_up:

#927 index updates & updating module statuses
  docs/content/indexes/bicep/bicep-pattern-modules.md
  docs/content/indexes/bicep/bicep-resource-modules.md
  docs/content/indexes/terraform/tf-pattern-modules.md
  docs/content/indexes/terraform/tf-resource-modules.md
  docs/layouts/shortcodes/moduleHistory.html
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/layouts/shortcodes/moduleNameTelemetryGHTeams.html
  docs/layouts/shortcodes/moduleStats.html
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
  utilities/pipelines/sharedScripts/teamLinter/Get-AvmCsvData.ps1
Labels: Type: Documentation :page_facing_up:, Type: Hygiene :broom:

#936 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#937 index update
  docs/static/governance/apiSpecsList.json
Labels: Needs: Triage :mag:

#941 index file update
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#878 fix: Worked in several feedback items for contribution guide
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/content/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files.md
  docs/content/contributing/bicep/bicep-contribution-flow/validate-bicep-module-locally.md
Labels: Type: Documentation :page_facing_up:

#943 fix: Fixed name of BRM workflow reference
  docs/content/contributing/bicep/bicep-contribution-flow/enable-or-disable-workflows.md
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#945 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#958 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#960 Index file update
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#969 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#971 Multiple updates tf index
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#967 newres in contribution guide
  docs/content/contributing/terraform/terraform-contribution-flow/_index.md
Labels: Needs: Triage :mag:

#978 Publish May 2024 Community Call
  docs/content/_index.md
  docs/content/resources/community/_index.md
Labels: Type: Documentation :page_facing_up:

#928 feat: Updated workflow names & template to latest convention in AVM-BRM
  docs/content/contributing/bicep/bicep-contribution-flow/enable-or-disable-workflows.md
  docs/static/includes/avm.[res-ptn].workflow.template.yml
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#976 Pmeshram/feat/updates
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#979 Update TerraformResourceModules.csv for cosmosdb
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#986 Update TerraformResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#987 Update TerraformResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#989 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#992 feat: Add New Labels
  docs/static/governance/avm-standard-github-labels.csv
Labels: Type: Hygiene :broom:

#984 feat: Adding closure for existing issues which have been resolved via the AVM Team Linter Bot
  utilities/pipelines/sharedScripts/teamLinter/Close-ResolvedGithubIssue.ps1
  utilities/pipelines/sharedScripts/teamLinter/Invoke-AvmGitHubTeamLinter.ps1
Labels: Type: Hygiene :broom:

#947 Introducing Utility Modules
  docs/content/specs-defs/module-classifications.md
Labels: Type: Documentation :page_facing_up:

#1003 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:
