Repository Azure/Azure-Verified-Modules, pull requests merged in 2024-12, with the labels that each got.

#1741 Update composition.md
  docs/content/contributing/terraform/composition.md
Labels: Needs: Triage :mag:

#1745 faq update
  docs/content/faq/_index.md
Labels: Needs: Triage :mag:

#1747 Feat/matebarabas/spec-link-updates
  .github/ISSUE_TEMPLATE/module_proposal.yml
  .github/ISSUE_TEMPLATE/orphaned_module.yml
  docs/layouts/shortcodes/tagsStats.html
  docs/static/includes/avm-terraform-module-review-template.md
  docs/static/includes/msg-final-conf-new-orph-mod-owners.md
  docs/static/includes/msg-final-conf-new-prop-mod-owners.md
  docs/static/includes/msg-std-reply-new-orph-mod-owners.md
  docs/static/includes/msg-std-reply-new-prop-mod-owners.md
  utilities/pipelines/sharedScripts/teamLinter/Invoke-AvmGitHubTeamLinter.ps1
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1748 dark mode button fixes for tag feature
  docs/content/specs-defs/specs/bicep/pattern/_index.md
  docs/layouts/shortcodes/tagsBasedNavigationTable.html
Labels: Type: Documentation :page_facing_up:

#1749 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1737 Added CMK schema, introduced type import & grouped interface files
  docs/content/specs-defs/includes/bicep/shared/functional/BCPFR1.md
  docs/content/specs-defs/includes/bicep/shared/non-functional/BCPNFR3.md
  docs/content/specs-defs/specs/bicep/resource/interfaces.md
  docs/content/specs-defs/specs/legacy/bicep/interfaces.md
  docs/content/specs-defs/specs/legacy/shared/interfaces.md
  docs/content/specs-defs/specs/terraform/resource/interfaces.md
  docs/static/includes/interfaces/bicep/int.cmk.input1.bicep
  docs/static/includes/interfaces/bicep/int.cmk.input2.bicep
  docs/static/includes/interfaces/bicep/int.cmk.udt.schema1.bicep
  docs/static/includes/interfaces/bicep/int.cmk.udt.schema2.bicep
  docs/static/includes/interfaces/bicep/int.diag.input1.bicep
  docs/static/includes/interfaces/bicep/int.diag.input2.bicep
  docs/static/includes/interfaces/bicep/int.diag.input3.bicep
  docs/static/includes/interfaces/bicep/int.diag.udt.schema1.bicep
  docs/static/includes/interfaces/bicep/int.diag.udt.schema2.bicep
  docs/static/includes/interfaces/bicep/int.diag.udt.schema3.bicep
  docs/static/includes/interfaces/bicep/int.locks.input.bicep
  docs/static/includes/interfaces/bicep/int.locks.udt.schema.bicep
  docs/static/includes/interfaces/bicep/int.mi.input1.bicep
  docs/static/includes/interfaces/bicep/int.mi.input2.bicep
  docs/static/includes/interfaces/bicep/int.mi.input3.bicep
  docs/static/includes/interfaces/bicep/int.mi.udt.schema1.bicep
  docs/static/includes/interfaces/bicep/int.mi.udt.schema2.bicep
  docs/static/includes/interfaces/bicep/int.mi.udt.schema3.bicep
  docs/static/includes/interfaces/bicep/int.pe.input1.bicep
  docs/static/includes/interfaces/bicep/int.pe.input2.bicep
  docs/static/includes/interfaces/bicep/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/bicep/int.pe.udt.schema2.bicep
  docs/static/includes/interfaces/bicep/int.rbac.input.bicep
  docs/static/includes/interfaces/bicep/int.rbac.udt.schema.bicep
  docs/static/includes/interfaces/bicep/int.secExp.input.bicep
  docs/static/includes/interfaces/bicep/int.secExp.module.bicep
  docs/static/includes/interfaces/bicep/int.secExp.output.bicep
  docs/static/includes/interfaces/bicep/int.secExp.output.jsonFmt.json
  docs/static/includes/interfaces/bicep/int.secExp.udt.schema.bicep
  docs/static/includes/interfaces/bicep/int.tags.input.bicep
  docs/static/includes/interfaces/bicep/int.tags.udt.schema.bicep
  docs/static/includes/interfaces/int.cmk.udt.schema.bicep
  docs/static/includes/interfaces/int.diag.udt.schema.bicep
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
  docs/static/includes/interfaces/tf/int.cmk.input.tf
  docs/static/includes/interfaces/tf/int.cmk.schema.tf
  docs/static/includes/interfaces/tf/int.diag.input.tf
  docs/static/includes/interfaces/tf/int.diag.schema.tf
  docs/static/includes/interfaces/tf/int.locks.input.tf
  docs/static/includes/interfaces/tf/int.locks.schema.tf
  docs/static/includes/interfaces/tf/int.mi.input.tf
  docs/static/includes/interfaces/tf/int.mi.schema.tf
  docs/static/includes/interfaces/tf/int.pe.input.tf
  docs/static/includes/interfaces/tf/int.pe.schema.tf
  docs/static/includes/interfaces/tf/int.rbac.input.tf
  docs/static/includes/interfaces/tf/int.rbac.schema.tf
  docs/static/includes/interfaces/tf/int.tags.input.tf
  docs/static/includes/interfaces/tf/int.tags.schema.tf
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#1756 Update avm-terraform-module-review-template.md
  docs/static/includes/avm-terraform-module-review-template.md
Labels: Needs: Triage :mag:

#1758 feat(tfnfr): change must to may for tfnfr1
  docs/content/specs-defs/includes/terraform/shared/non-functional/TFNFR1.md
Labels: Needs: Triage :mag:

#1759 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1754 triage automation updates
  .github/policies/eventResponder.yml
  .github/policies/scheduledSearches.yml
  docs/content/help-support/issue-triage/issue-triage-automation.md
Labels: Type: Documentation :page_facing_up:, Type: Hygiene :broom:

#1762 fix: Update links to brm `utilities` folder
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/content/contributing/bicep/bicep-contribution-flow/enable-or-disable-workflows.md
  docs/content/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files.md
  docs/content/contributing/bicep/bicep-contribution-flow/validate-bicep-module-locally.md
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/specs-defs/includes/shared/shared/functional/SFR3.md
  docs/static/includes/avm.workflow.template.yml
  docs/static/scripts/sample-localtest-helper.ps1
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#1750 doc updates - adding Quickstart Guide for Bicep and TF
  docs/config.toml
  docs/content/contributing/website/_index.md
  docs/content/faq/_index.md
  docs/content/usage/quickstart/_index.md
  docs/content/usage/quickstart/bicep/_index.md
  docs/content/usage/quickstart/terraform/_index.md
  docs/data/menu/main.yaml
  docs/layouts/partials/page-header.html
  docs/static/img/faq/use-bicep-module-01.png
  docs/static/img/faq/use-bicep-module-02.png
  docs/static/img/faq/use-bicep-module-03.png
  docs/static/img/faq/use-bicep-module-04.png
  docs/static/img/faq/use-bicep-module-05.png
  docs/static/img/faq/use-bicep-module-06.png
  docs/static/img/usage/quickstart/bicep/key-vault-readme-bcp-1080-10fps.mp4
  docs/static/img/usage/quickstart/bicep/key-vault-vscode-bcp-1080-10fps.mp4
  docs/static/img/usage/quickstart/bicep/kv-and-secret-vs-code-intellisense-bcp-1080-10fps.mp4
  docs/static/img/usage/quickstart/bicep/module-index_bcp_res_1080-10fps.mp4
  docs/static/img/usage/quickstart/bicep/vs-code-intellisense-bcp-1080-10fps.mp4
  docs/static/img/usage/quickstart/terraform/avm-qs-tf-commands-1080-10.mp4
  docs/static/img/usage/quickstart/terraform/avm-tf-qa-discovery-1080-10.mp4
  docs/static/img/usage/quickstart/terraform/avm-tf-qs-custom-full-1080-10.mp4
  docs/static/img/usage/quickstart/terraform/avm-tf-qs-discovery-1080-10.mp4
  docs/static/img/usage/quickstart/terraform/avm-tf-qs-example-copy-1080-10.mp4
  docs/static/img/usage/quickstart/terraform/avm-tf-qs-example-vscode-1080-10.mp4
  docs/static/img/usage/quickstart/terraform/avm-tf-search-5-10.gif
  docs/static/img/usage/quickstart/terraform/avm-tf-search-5.mp4
  docs/static/img/usage/quickstart/terraform/avm-tf-search-6-10.mp4
  docs/static/img/usage/quickstart/terraform/module-index_tf_res_1080-10fps.mp4
  docs/static/js/clarity.js
Labels: Type: Documentation :page_facing_up:

#1763 doc updates 3
  docs/content/_index.md
  docs/content/usage/_index.md
  docs/content/usage/deployment-options/temp.md
  docs/content/usage/quickstart/bicep/_index.md
  docs/content/usage/quickstart/terraform/_index.md
Labels: Type: Documentation :page_facing_up:

#1765 Feat/doc updates 4
  docs/content/usage/quickstart/terraform/_index.md
Labels: Needs: Triage :mag:
