Repository Azure/Azure-Verified-Modules, pull requests merged in 2024-09, with the labels that each got.

#1358 module index updates
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#1329 feat: Document 'custom secrets / passthru' feature
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/content/contributing/bicep/bicep-contribution-flow/custom-ci-secrets.md
  docs/data/menu/main.yaml
  docs/static/img/contribution/secrets/kvltSecret-exampleSecrets.png
  docs/static/img/contribution/secrets/kvltSecret-ghSetting.png
  docs/static/img/contribution/secrets/kvltSecret-pipelineLog.png
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1359 remove banner from main page
  docs/content/_index.md
Labels: Type: Documentation :page_facing_up:

#1367 fix: Custom Secrets - Small formatting updates & added disclaimer
  docs/content/contributing/bicep/bicep-contribution-flow/custom-ci-secrets.md
  docs/content/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files.md
Labels: Needs: Triage :mag:

#1368 fix: Fixed typos in RBAC schema
  docs/static/includes/interfaces/int.rbac.udt.schema.bicep
Labels: Needs: Triage :mag:

#1372 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1371 Fix output name for SAMI
  docs/static/includes/interfaces/int.mi.udt.schema.bicep
Labels: Needs: Triage :mag:

#1375 TF index update1
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
  docs/static/module-indexes/TerraformUtilityModules.csv
Labels: Needs: Triage :mag:

#1373 Bicep pattern module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#1379 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1385 Remove MCSB from security list of sources for "WAF Alignment"
  docs/config.toml
  docs/content/faq/_index.md
  docs/content/specs-defs/specs/shared/_index.md
Labels: Type: Documentation :page_facing_up:, Needs: Core Team :genie:

#1374 fix: Added PSRule workaround to docs
  docs/content/contributing/bicep/bicep-contribution-flow/custom-ci-secrets.md
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#1364 Added additional readme generation guidelines
  docs/content/contributing/bicep/bicep-contribution-flow/generate-bicep-module-files.md
Labels: Type: Documentation :page_facing_up:

#1390 Prjelesi index update
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1395 Updated the Community call page
  docs/content/resources/community/_index.md
Labels: Needs: Triage :mag:

#1394 Add release branch workflow and environment secrets to docs
  docs/content/contributing/terraform/terraform-contribution-flow/_index.md
  docs/content/contributing/terraform/terraform-contribution-flow/owner-contribution-flow.md
Labels: Needs: Triage :mag:

#1400 community call banner
  docs/content/_index.md
  docs/content/resources/community/_index.md
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1404 index update tf
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1413 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/BicepUtilityModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1418 Bicep pattern module updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#1425 Update review.md
  docs/content/contributing/terraform/review.md
Labels: Needs: Triage :mag:

#1116 add: Bicep deprecation sample
  docs/content/contributing/bicep/composition.md
  docs/content/specs-defs/specs/shared/_index.md
  docs/static/governance/avm-standard-github-labels.csv
Labels: Type: Documentation :page_facing_up:, Needs: Core Team :genie:

#1433 Add September 2024 Community Call
  docs/content/resources/community/_index.md
  docs/static/assets/community/may24/avm-community-call-may24.pdf
  docs/static/assets/community/sept24/avm-community-call-sept24.pdf
Labels: Needs: Triage :mag:

#1437 Update community call banner
  docs/content/_index.md
Labels: Type: Documentation :page_facing_up:

#1440 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1442 Update _index.md
  docs/content/contributing/terraform/terraform-contribution-flow/_index.md
Labels: Needs: Triage :mag:
