Repository Azure/Azure-Verified-Modules, pull requests merged in 2024-10, with the labels that each got.

#1447 fix: Small changes to secret export interface description to be more explicit
  docs/static/includes/interfaces/int.secExp.input.bicep
  docs/static/includes/interfaces/int.secExp.module.bicep
  docs/static/includes/interfaces/int.secExp.output.bicep
  docs/static/includes/interfaces/int.secExp.output.jsonFmt.json
  docs/static/includes/interfaces/int.secExp.udt.schema.bicep
Labels: Needs: Triage :mag:

#1460 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1469 avm-tf-module-index-update
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
  docs/static/module-indexes/TerraformUtilityModules.csv
Labels: Needs: Triage :mag:

#1497 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1503 Bicep module index updates
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1118 feat: add devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitattributes
Labels: Type: Documentation :page_facing_up:, Needs: Core Team :genie:

#1547 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1539 opentofu statement added
  docs/content/faq/_index.md
Labels: Type: Documentation :page_facing_up:

#1531 feat: Add script to parse WAF security recommendations and generate C…
  utilities/tools/platform/Parse-WAF-Security-Recommendations.py
Labels: Needs: Triage :mag:

#1554 docs: AVM documentation issue template
  .github/ISSUE_TEMPLATE/documentation_update.yml
Labels: Type: Documentation :page_facing_up:

#1558 fix: Updated regex for types in feature table update logic
  utilities/tools/platform/helper/Get-ModulesFeatureOutline.ps1
Labels: Type: Bug :bug:

#1567 Prjelesi/indexupdate 1810
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1574 Update avm triage to include new issue template
  docs/content/help-support/issue-triage/avm-issue-triage.md
Labels: Type: Documentation :page_facing_up:

#1591 fix: Fixed schema descriptions
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
Labels: Needs: Triage :mag:, Type: Bug :bug:, Type: Documentation :page_facing_up:

#1592 avm-tf-module-index-update
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1599 chore: update terraform contribution guide
  docs/content/contributing/terraform/terraform-contribution-flow/owner-contribution-flow.md
Labels: Needs: Triage :mag:

#1519 Improve contribution doc
  docs/content/contributing/process.md
  docs/content/specs-defs/specs/shared/_index.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1623 SNFR20 update
  docs/content/specs-defs/specs/shared/_index.md
Labels: Type: Documentation :page_facing_up:

#1419 add RMFR8 - Category: Composition - End-of-life resource versions
  docs/content/specs-defs/specs/shared/_index.md
Labels: Type: Documentation :page_facing_up:

#1642 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:
