Repository Azure/Azure-Verified-Modules, pull requests merged in 2024-01, with the labels that each got.

#377 feat: add toggle workflow description
  .github/linters/.markdown-lint.yml
  docs/content/contributing/bicep/bicep-contribution-flow/enable-or-disable-workflows.md
  docs/data/menu/main.yaml
  docs/static/img/contribution/runToggleWorkflows.png
  docs/static/img/contribution/selectToggleWorkflows.png
Labels: Type: Documentation :page_facing_up:

#483 fix: wording around duplication of issues for AVM Team Linter
  utilities/pipelines/sharedScripts/teamLinter/Set-AvmGitHubTeamsIssue.ps1
Labels: Needs: Triage :mag:

#481 fix: Fixed metadata of Diagnostic Settings Type Metrics
  docs/static/includes/interfaces/int.diag.udt.schema.bicep
Labels: Needs: Triage :mag:, Type: Bug :bug:, Type: AVM :a: :v: :m:, Language: Bicep :muscle:

#485 Bicep resource module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#426 Suggested resource example to MI (`managed_identities`) interface for Terraform
  docs/static/includes/interfaces/int.mi.schema.tf
Labels: Needs: Attention :wave:

#487 ITA24 - update scheduled search
  .github/policies/scheduledSearches.yml
Labels: Type: Documentation :page_facing_up:

#495 Bicep resource module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#494 fix: Update workflows gh runner image version to ubuntu-latest
  .github/workflows/platform.apiSpecs.yml
  .github/workflows/platform.updateModuleRegistryTables.yml
  docs/static/includes/avm.[res-res].template.pattern.yml
Labels: Needs: Triage :mag:

#499 fix: Update image urls
  docs/content/contributing/bicep/bicep-contribution-flow/enable-or-disable-workflows.md
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#500 fix: Remove RG example to RMFR2
  docs/content/specs/shared/_index.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#503 Bicep resource module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#486 update SNFR20 with direct link to GH team creation
  docs/content/contributing/q-and-a.md
  docs/content/faq/_index.md
  docs/content/help-support/issue-triage/brm-issue-triage.md
  docs/content/specs/shared/_index.md
  docs/content/specs/shared/module-lifecycle.md
Labels: Type: Documentation :page_facing_up:

#504 Update TerraformPatternModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
Labels: Needs: Triage :mag:

#517 Bicep resource module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#516 Added cicd pattern module
  docs/static/module-indexes/TerraformPatternModules.csv
Labels: Needs: Triage :mag:

#498 fix: Update avm workflow template
  docs/static/includes/avm.[res-res].template.pattern.yml
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#522 fix: tf spec title
  docs/content/specs/terraform/_index.md
Labels: Type: Documentation :page_facing_up:, Type: Hygiene :broom:

#521 docs: remove codeowners requirement for terraform
  docs/content/specs/shared/_index.md
Labels: Needs: Triage :mag:

#524 Update Support Messaging
  docs/content/_index.md
  docs/content/help-support/module-support.md
Labels: Type: Documentation :page_facing_up:

#535 docs: update versions spec for terraform
  docs/content/specs/terraform/_index.md
Labels: Needs: Triage :mag:

#519 feat: Simplified MSI output
  docs/static/includes/interfaces/int.mi.udt.schema.bicep
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#541 Bicep resource module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#543 Bicep resource module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#554 Bicep resource module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#556 Update preview notice wording
  docs/content/contributing/process.md
Labels: Type: Documentation :page_facing_up:

#569 Bicep index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#549 feat: add BCPNFR15 to include AVM module issue template update guidelines
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/specs/bicep/_index.md
Labels: Type: Documentation :page_facing_up:

#572 Pmeshram/feat/updates
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#573 Add Youtube Intro Video
  docs/content/_index.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#536 fix: cmk interface default
  docs/static/includes/interfaces/int.cmk.schema.tf
Labels: Needs: Triage :mag:

#579 Pmeshram/feat/updates
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#580 Pmeshram/feat/updates
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#583 Bicep index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:
