Repository Azure/Azure-Verified-Modules, pull requests merged in 2024-02, with the labels that each got.

#600 Bicep resource module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#544 fix: Bicep - Updated formatting and fixed outdated descriptors
  docs/static/includes/interfaces/int.cmk.udt.schema.bicep
  docs/static/includes/interfaces/int.diag.udt.schema.bicep
  docs/static/includes/interfaces/int.locks.udt.schema.bicep
  docs/static/includes/interfaces/int.mi.udt.schema.bicep
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
  docs/static/includes/interfaces/int.rbac.udt.schema.bicep
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#607 Introduce CODEOWNERS file
  .github/CODEOWNERS
Labels: Needs: Triage :mag:, Type: Hygiene :broom:

#609 fix: add permissions section to bicep workflow template
  docs/static/includes/avm.[res-res].template.pattern.yml
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#608 Added tip for Toggle-Status workflow
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
Labels: Type: Documentation :page_facing_up:

#605 FAQ updates
  docs/content/_index.md
  docs/content/faq/_index.md
  docs/content/help-support/module-support.md
  docs/content/specs/terraform/_index.md
Labels: Needs: Triage :mag:

#614 Index Update
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#629 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#512 feat: terraform contribution guide
  .gitignore
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/content/contributing/terraform/_index.md
  docs/content/contributing/terraform/composition.md
  docs/content/contributing/terraform/prerequisites.md
  docs/content/contributing/terraform/terraform-contribution-flow/_index.md
  docs/content/contributing/terraform/terraform-contribution-flow/owner-contribution-flow.md
  docs/data/menu/main.yaml
  docs/static/img/contribution/deploymentProtectionRules.png
  docs/static/img/contribution/deploymentProtectionRules2.png
  docs/static/img/contribution/deploymentProtectionTeams.png
  docs/static/img/contribution/forkUpstream.png
  docs/static/img/contribution/gitTag.png
  docs/static/img/contribution/pullImage.png
Labels: Type: Documentation :page_facing_up:, Language: Terraform :globe_with_meridians:

#636 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#637 fix: Fixed schema for Bicep Diagnostic Settings
  docs/static/includes/interfaces/int.diag.input.bicep
  docs/static/includes/interfaces/int.diag.udt.schema.bicep
Labels: Type: Documentation :page_facing_up:

#639 feat: Changed module feature CSV order to alphabetical
  utilities/tools/platform/helper/Get-ModulesFeatureOutline.ps1
Labels: Needs: Triage :mag:, Language: Bicep :muscle:

#644 FAQ updates
  docs/content/faq/_index.md
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/specs/shared/team-definitions.md
  docs/data/menu/main.yaml
Labels: Type: Documentation :page_facing_up:

#649 adding AVM customer presentation
  docs/content/resources/AVM-Overview-Customer-presentation.pdf
  docs/content/resources/_index.md
  docs/data/menu/main.yaml
Labels: Type: Documentation :page_facing_up:

#650 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#651 Pmeshram/feat/updates
  docs/content/specs/terraform/_index.md
Labels: Type: Documentation :page_facing_up:

#664 Bicep pattern module updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Needs: Triage :mag:

#665 Bicep pattern module index update
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Needs: Triage :mag:

#537 fix: update PE spec to work with Azure Policy
  docs/static/includes/interfaces/int.mi.schema.tf
  docs/static/includes/interfaces/int.pe.schema.tf
  docs/static/includes/interfaces/int.rbac.schema.tf
  docs/static/includes/interfaces/int.tags.schema.tf
Labels: Type: Documentation :page_facing_up:

#676 Feat/matebarabas/index-updates
  docs/content/resources/_index.md
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#621 PE schema adjustments
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
Labels: Type: Documentation :page_facing_up:

#692 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#691 AVM triage updates
  docs/content/help-support/issue-triage/avm-issue-triage.md
Labels: Type: Documentation :page_facing_up:

#689 fix: Fixed prefix & suffix for Bicep schemas as they were unintendedly interpreted in some cases
  docs/static/includes/interfaces/int.cmk.udt.schema.bicep
  docs/static/includes/interfaces/int.diag.udt.schema.bicep
  docs/static/includes/interfaces/int.locks.udt.schema.bicep
  docs/static/includes/interfaces/int.mi.udt.schema.bicep
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
  docs/static/includes/interfaces/int.rbac.udt.schema.bicep
Labels: Type: Bug :bug:, Type: Documentation :page_facing_up:

#694 fix: TF guide updates
  docs/content/contributing/terraform/terraform-contribution-flow/owner-contribution-flow.md
Labels: Needs: Triage :mag:

#696 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:
