Repository Azure/Azure-Verified-Modules, pull requests merged in 2024-03, with the labels that each got.

#702 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#623 Fix - refactor `customer_managed_key` interface type
  docs/static/includes/interfaces/int.cmk.schema.tf
Labels: Type: Documentation :page_facing_up:, Language: Terraform :globe_with_meridians:

#662 Pmeshram/feat/updates - updated TF Res Indexes
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#683 Update github label scripts and instructions
  docs/content/specs/shared/_index.md
  docs/static/scripts/Set-AvmGitHubLabels.ps1
Labels: Needs: Triage :mag:

#718 Index Update
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#720 Bicep index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#719 adding reference to new lab content
  docs/content/resources/_index.md
Labels: Type: Documentation :page_facing_up:

#721 Fix typo in what-why-how.md
  docs/content/concepts/what-why-how.md
Labels: Needs: Triage :mag:

#723 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Needs: Triage :mag:

#724 update customer presentation
  docs/content/resources/AVM-Overview-Customer-presentation.pdf
Labels: Type: Documentation :page_facing_up:

#727 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#737 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#739 Update TF triage automation documentation
  docs/content/help-support/issue-triage/issue-triage-automation.md
Labels: Type: Documentation :page_facing_up:

#740 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#742 Terraform PG Team Update
  docs/content/contributing/terraform/terraform-contribution-flow/owner-contribution-flow.md
  docs/content/specs/shared/_index.md
  docs/content/specs/shared/team-definitions.md
  docs/content/specs/terraform/_index.md
Labels: Type: Documentation :page_facing_up:

#743 Add community content to resources page
  docs/content/resources/_index.md
Labels: Needs: Triage :mag:

#745 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#750 Update TerraformResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#756 Bicep and TF index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#765 Update TerraformResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#768 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#763 Triage automation and documentation improvements
  .github/policies/eventResponder.yml
  .github/policies/scheduledSearches.yml
  docs/content/help-support/issue-triage/brm-issue-triage.md
  docs/content/help-support/issue-triage/issue-triage-automation.md
Labels: Type: Documentation :page_facing_up:, Type: Hygiene :broom:

#777 triage automation fix
  .github/policies/eventResponder.yml
Labels: Type: Documentation :page_facing_up:, Type: Hygiene :broom:

#784 triage automation bug fixes
  .github/policies/eventResponder.yml
  docs/content/help-support/issue-triage/issue-triage-automation.md
Labels: Type: Hygiene :broom:

#717 feat: Add `Bicep Owner Contribution Flow` and `Contributor Checklist`
  docs/content/contributing/bicep/bicep-contribution-flow/owner-contribution-flow.md
  docs/content/contributing/bicep/prerequisites.md
  docs/data/menu/main.yaml
  docs/static/img/contribution/gh_notifications_page.png
  docs/static/img/contribution/gh_watch.png
Labels: Needs: Triage :mag:

#762 feat: Added the ability to specify a custom resource group when deploying a private endpoint
  docs/static/includes/interfaces/int.pe.input.bicep
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
Labels: Type: Documentation :page_facing_up:

#785 feat: Add `Bicep Owner Contribution Flow` and `Contributor Checklist`…
  docs/content/contributing/bicep/bicep-contribution-flow/owner-contribution-flow.md
  docs/content/contributing/bicep/prerequisites.md
  docs/data/menu/main.yaml
  docs/static/img/contribution/gh_notifications_page.png
  docs/static/img/contribution/gh_watch.png
  docs/static/scripts/sample-localtest-helper.ps1
Labels: Type: Documentation :page_facing_up:

#789 feature: Updated formatting on table of conten
  docs/content/contributing/bicep/bicep-contribution-flow/owner-contribution-flow.md
Labels: Type: Documentation :page_facing_up:

#790 Update TerraformResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#728 feat: Updated `TF Contribution Guide` and aligned with `Bicep Contribution Guide`
  .gitignore
  docs/content/contributing/bicep/bicep-contribution-flow/owner-contribution-flow.md
  docs/content/contributing/terraform/prerequisites.md
  docs/content/contributing/terraform/terraform-contribution-flow/_index.md
  docs/content/contributing/terraform/terraform-contribution-flow/owner-contribution-flow.md
  docs/content/specs/terraform/_index.md
Labels: Needs: Triage :mag:

#791 update terraform res index
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#792 Bicep index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#771 fix: incorrect attribute name in system MI helper example
  docs/static/includes/interfaces/int.mi.schema.tf
Labels: Needs: Triage :mag:

#798 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:
