Repository Azure/Azure-Verified-Modules, pull requests merged in 2024-06, with the labels that each got.

#1002 Added FAQ item
  docs/content/faq/_index.md
Labels: Needs: Triage :mag:

#988 avm-tf-modules-review-doc
  docs/content/contributing/terraform/review.md
  docs/content/contributing/terraform/terraform-contribution-flow/_index.md
  docs/content/contributing/terraform/terraform-contribution-flow/owner-contribution-flow.md
  docs/data/menu/main.yaml
  docs/static/includes/avm-terraform-module-review-template.md
Labels: Type: Documentation :page_facing_up:

#1010 Pmeshram/feat/updates
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1012 updated triage automation notifications
  .github/policies/eventResponder.yml
  .github/policies/scheduledSearches.yml
  docs/content/help-support/issue-triage/issue-triage-automation.md
Labels: Type: Documentation :page_facing_up:, Type: Hygiene :broom:

#996 fix: Update sem ver spec SNFR17
  docs/content/specs-defs/specs/shared/_index.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:, Type: AVM :a: :v: :m:

#1018 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/BicepUtilityModules.csv
Labels: Type: Documentation :page_facing_up:

#1022 feat: Removing schedule from pipeline template
  docs/static/includes/avm.[res-ptn].workflow.template.yml
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1019 introducing index pages for utility modules
  docs/content/indexes/_index.md
  docs/content/indexes/bicep/_index.md
  docs/content/indexes/bicep/bicep-utility-modules.md
  docs/content/indexes/terraform/_index.md
  docs/content/indexes/terraform/tf-utility-modules.md
  docs/data/menu/main.yaml
  docs/layouts/shortcodes/moduleHistory.html
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/layouts/shortcodes/moduleNameTelemetryGHTeams.html
  docs/layouts/shortcodes/moduleStats.html
  docs/static/module-indexes/TerraformUtilityModules.csv
Labels: Type: Documentation :page_facing_up:

#1021 Doc improvements
  docs/content/contributing/bicep/composition.md
Labels: Type: Documentation :page_facing_up:

#1033 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#1025 adding new emoji "Type: CI :rocket:"
  docs/static/governance/avm-standard-github-labels.csv
Labels: Type: Documentation :page_facing_up:

#1042 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#1043 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1049 adding link to ongoing module maintenance wiki
  docs/content/contributing/bicep/bicep-contribution-flow/owner-contribution-flow.md
Labels: Type: Documentation :page_facing_up:

#1059 Correct tags schema in private_endpoints variable
  docs/static/includes/interfaces/int.pe.schema.tf
Labels: Needs: Triage :mag:

#1058 Update TerraformResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1107 module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1108 Index file update
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1109 update index pages with links to modules needing owners or contributors
  docs/content/faq/_index.md
  docs/content/indexes/_index.md
  docs/content/indexes/bicep/_index.md
  docs/content/indexes/terraform/_index.md
  docs/static/governance/avm-standard-github-labels.csv
Labels: Type: Documentation :page_facing_up:

#1120 Update TerraformResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1121 adding guidance for using the needs core team label
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/content/contributing/bicep/bicep-contribution-flow/owner-contribution-flow.md
  docs/content/help-support/issue-triage/brm-issue-triage.md
  docs/content/help-support/issue-triage/issue-triage-automation.md
Labels: Type: Documentation :page_facing_up:

#1123 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1122 adding saved query to BRM triage documentation
  docs/content/help-support/issue-triage/brm-issue-triage.md
Labels: Type: Documentation :page_facing_up:

#1028 revise terraform output specs
  docs/content/specs-defs/specs/terraform/_index.md
Labels: Needs: Triage :mag:, Language: Terraform :globe_with_meridians:

#1131 Update TerraformResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1134 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1001 Remove ambiguity for the private endpoint spec
  docs/static/includes/interfaces/int.pe.schema.tf
Labels: Type: Documentation :page_facing_up:, Needs: Core Team :genie:

#1124 feat: Updated telemetry template to latest Bicep convention
  docs/static/includes/sample.telem.bicep
Labels: Type: Documentation :page_facing_up:

#1140 AVM-TF-Module-Index-Update-06252024
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1142 Bicep module index update
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1129 index update
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformUtilityModules.csv
Labels: Needs: Triage :mag:

#1149 feat: Add Bicep Contribution Repo & CI Setup Script
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/static/scripts/New-AVMBicepBRMForkSetup.ps1
Labels: Needs: Core Team :genie:

#1152 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:
