Repository Azure/Azure-Verified-Modules, pull requests merged in 2024-08, with the labels that each got.

#1260 AVM FT Module Index Update
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1257 Pmeshram/feat/updates
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1261 feat: Added 'Secret Exports' schema for Bicep
  docs/content/specs-defs/specs/_index.md
  docs/content/specs-defs/specs/bicep/interfaces.md
  docs/data/menu/main.yaml
  docs/static/includes/interfaces/int.cmk.udt.schema.bicep
  docs/static/includes/interfaces/int.diag.udt.schema.bicep
  docs/static/includes/interfaces/int.locks.udt.schema.bicep
  docs/static/includes/interfaces/int.mi.udt.schema.bicep
  docs/static/includes/interfaces/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/int.pe.udt.schema2.bicep
  docs/static/includes/interfaces/int.rbac.udt.schema.bicep
  docs/static/includes/interfaces/int.secExp.input.bicep
  docs/static/includes/interfaces/int.secExp.module.bicep
  docs/static/includes/interfaces/int.secExp.output.bicep
  docs/static/includes/interfaces/int.secExp.output.jsonFmt.json
  docs/static/includes/interfaces/int.secExp.udt.schema.bicep
Labels: Language: Bicep :muscle:

#1270 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1271 Feat/matebarabas/update-index-summary-tables
  docs/layouts/partials/countModules.html
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/layouts/shortcodes/moduleStats.html
Labels: Type: Documentation :page_facing_up:

#1272 index update HCI
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1283 adding secondary owners to TF index pages
  docs/layouts/shortcodes/moduleNameStatusOwners.html
Labels: Type: Documentation :page_facing_up:

#1280 Avm tf module review
  docs/content/contributing/terraform/review.md
  docs/static/includes/avm-terraform-module-review-template.md
Labels: Needs: Triage :mag:

#1292 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#1302 oracle index
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1306 module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1307 Terraform module index updates
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1315 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#1326 fix: Module status table update fix
  utilities/tools/platform/helper/Get-ModulesFeatureOutline.ps1
Labels: Type: Bug :bug:, Type: Documentation :page_facing_up:, Type: CI :rocket:

#1335 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1337 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#1339 Updated the module published in Aug
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1345 Avm tf module index
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:
