Repository Azure/Azure-Verified-Modules, pull requests merged in 2025-03, with the labels that each got.

#1890 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1893 Pmeshram/feat/updates main
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1896 Pmeshram/feat/updates main
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1796 feat: Added documentation for skipping test deployments
  docs/content/specs-defs/includes/shared/shared/non-functional/SNFR2.md
Labels: Needs: Triage :mag:

#1899 adding licensing question to FAQ
  docs/content/resources/faq.md
Labels: Type: Documentation :page_facing_up:

#1894 docs: update terraform module owner contribution guidance
  docs/content/contributing/terraform/terraform-contribution-flow/owner-contribution-flow.md
  docs/content/contributing/terraform/terraform-contribution-flow/repository-creation-process.md
  docs/hugo.toml
Labels: Status: In PR :point_right:

#1900 Bicep index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#1908 Updated the module owner details of avm-res-analysisservices-server
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1898 Pmeshram/feat/updates main
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1915 Bicep module index updates
  docs/content/usage/sol-dev.md
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1870 feat: Introduce Zone-Redundancy interface for Bicep
  docs/content/specs-defs/specs/bicep/interfaces.md
  docs/static/includes/interfaces/bicep/int.zone.input1.bicep
  docs/static/includes/interfaces/bicep/int.zone.input2.bicep
  docs/static/includes/interfaces/bicep/int.zone.schema1.bicep
  docs/static/includes/interfaces/bicep/int.zone.schema2.bicep
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:, Needs: Core Team :genie:

#1918 triage link updates
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/usage/sol-dev.md
Labels: Type: Documentation :page_facing_up:

#1928 feat: new utility module
  docs/static/module-indexes/TerraformUtilityModules.csv
Labels: Needs: Triage :mag:

#1930 fix: registry lookup for non azurerm modules
  docs/layouts/shortcodes/moduleHistory.html
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/static/module-indexes/TerraformUtilityModules.csv
Labels: Type: Bug :bug:
