Repository Azure/Azure-Verified-Modules, pull requests merged in 2025-02, with the labels that each got.

#1831 fix: broken links to module specs
  docs/content/contributing/q-and-a.md
Labels: Needs: Triage :mag:

#1836 updated the index file for TF resource module
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1837 Pmeshram/feat/updates main
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1838 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1840 Pmeshram/feat/updates main
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1843 adding content for the CC of Feb 2025
  docs/content/_index.md
  docs/content/resources/community.md
  docs/static/community/avm-community-call-feb25.pdf
Labels: Type: Documentation :page_facing_up:

#1844 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1845 adding website updates video
  docs/content/resources/community.md
Labels: Type: Documentation :page_facing_up:

#1847 Pmeshram/feat/updates main
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1850 feat: Added a known issue when using an SPN for OIDC
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#1851 fix: Updated PE schema to latest validated working version
  docs/static/includes/interfaces/bicep/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/bicep/int.pe.udt.schema2.bicep
Labels: Type: Bug :bug:, Type: Documentation :page_facing_up:

#1858 feat: Simplified several Bicep specs as per latest DSL improvements
  docs/static/includes/interfaces/bicep/int.cmk.udt.schema1.bicep
  docs/static/includes/interfaces/bicep/int.cmk.udt.schema2.bicep
  docs/static/includes/interfaces/bicep/int.secExp.output.bicep
  docs/static/includes/interfaces/bicep/int.secExp.udt.schema.bicep
Labels: Needs: Triage :mag:

#1864 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1867 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#1860 [Documentation-Update]: Cross referenced Modules (Bicep)
  docs/content/specs-defs/includes/bicep/shared/functional/BCPFR7.md
  docs/content/specs-defs/includes/shared/shared/functional/SFR4.md
Labels: Needs: Triage :mag:

#1879 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#1881 Bicep index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1882 fix bug of not showing GitHub teams for pattern and utility modules on the website
  docs/layouts/shortcodes/moduleNameTelemetryGHTeams.html
Labels: Type: Documentation :page_facing_up:

#1877 fix: Link in spec overview pages
  docs/layouts/shortcodes/tagsBasedNavigationTable.html
Labels: Type: Documentation :page_facing_up:

#1848 feat: Bicep changelog spec
  docs/content/specs-defs/includes/bicep/shared/non-functional/BCPNRF22.md
Labels: Type: Documentation :page_facing_up:
