Repository Azure/Azure-Verified-Modules, pull requests merged in 2025-05, with the labels that each got.

#2006 fix broken image on Readme
  README.md
Labels: Needs: Triage :mag:

#2008 additional information for orphaned modules
  docs/content/help-support/module-support.md
Labels: Type: Documentation :page_facing_up:

#2018 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#2019 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#2056 Bicep index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#2057 Bicep index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1910 docs: Adding solution development guidance to the Azure Verified Modules usage guide
  docs/content/usage/_index.md
  docs/content/usage/concepts.md
  docs/content/usage/includes/bicep-prerequisites.md
  docs/content/usage/includes/bicep/VirtualMachineAVM_Example1/steps/step1.bicep
  docs/content/usage/includes/bicep/VirtualMachineAVM_Example1/steps/step10.bicep
  docs/content/usage/includes/bicep/VirtualMachineAVM_Example1/steps/step11.bicep
  docs/content/usage/includes/bicep/VirtualMachineAVM_Example1/steps/step12.bicep
  docs/content/usage/includes/bicep/VirtualMachineAVM_Example1/steps/step2.bicep
  docs/content/usage/includes/bicep/VirtualMachineAVM_Example1/steps/step3.bicep
  docs/content/usage/includes/bicep/VirtualMachineAVM_Example1/steps/step4.bicep
  docs/content/usage/includes/bicep/VirtualMachineAVM_Example1/steps/step5.bicep
  docs/content/usage/includes/bicep/VirtualMachineAVM_Example1/steps/step6.bicep
  docs/content/usage/includes/bicep/VirtualMachineAVM_Example1/steps/step7.bicep
  docs/content/usage/includes/bicep/VirtualMachineAVM_Example1/steps/step8.bicep
  docs/content/usage/includes/bicep/VirtualMachineAVM_Example1/steps/step9.bicep
  docs/content/usage/includes/terraform-prerequisites.md
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step1-terraform.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step10-natgw.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step11-vnet.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step12-bastion.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step13-virtualmachine.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step14-main.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step15-outputs.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step16-terraform.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step17-nsg.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step2-variables.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step3-development.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step4-main-rg-novars.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step4a-main-rg.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step5-terraform-features.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step6-main-law.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step7-clientconfig.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step8-random-string.tf
  docs/content/usage/includes/terraform/VirtualMachineAVM_Example1/steps/step9-key-vault-module.tf
  docs/content/usage/quickstart/bicep.md
  docs/content/usage/quickstart/terraform.md
  docs/content/usage/sol-dev.md
  docs/content/usage/solution-development/_index.md
  docs/content/usage/solution-development/bicep.md
  docs/content/usage/solution-development/terraform.md
  docs/hugo.toml
  docs/layouts/shortcodes/code.html
  docs/static/community/avm-community-call-feb25.pdf
  docs/static/community/avm-community-call-may24-LAPTOP-A0LOVJ6V-2.pdf
  docs/static/community/avm-community-call-may24-LAPTOP-A0LOVJ6V.pdf
  docs/static/community/avm-community-call-may24.pdf
  docs/static/images/usage/concepts/pipelineOrchestration.png
  docs/static/images/usage/concepts/templateOrchestration.png
  docs/static/images/usage/solution-development/avm-virtualmachine-example1-tf.png
  docs/static/images/usage/solution-development/avm-virtualmachine-example1-tf.vsdx
  docs/static/images/usage/solution-development/avm-virtualmachine-example1.png
  docs/static/images/usage/solution-development/avm-virtualmachine-example1.vsdx
Labels: Type: Documentation :page_facing_up:

#2061 Pmeshram/feat/updates main
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#2066 Pmeshram/feat/updates main
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#2068 feat: new solution doc updates & contributing updates
  docs/content/contributing/website.md
  docs/content/usage/concepts.md
  docs/content/usage/solution-development/bicep.md
Labels: Type: Documentation :page_facing_up:

#2069 Bicep index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#2065 fix: Add support for RDTs for Tags
  utilities/tools/platform/helper/Get-ModulesFeatureOutline.ps1
Labels: Type: Bug :bug:

#2074 ITA04 and ITA24 update
  .github/policies/scheduledSearches.yml
  docs/content/help-support/issue-triage/issue-triage-automation.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#2078 fix: Removed redundant fallback value
  docs/static/includes/interfaces/bicep/int.zone.schema2.bicep
Labels: Type: Bug :bug:, Type: Documentation :page_facing_up:

#2084 fix: Added merge from main to modules CSV update to have it used latest codebase
  .github/workflows/platform.updateModuleRegistryTables.yml
  docs/static/includes/module-features/bicepBadges.md
  docs/static/includes/module-features/bicepFeatures.csv
Labels: Type: Bug :bug:, Type: CI :rocket:

#2090 add link to build recording
  docs/content/_index.md
  docs/content/resources/_index.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#2085 Transfer module `avm-res-communication-emailservice`'s ownership to lonegunmanb
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#2088 Change heading from "Bicep" to "Terraform" on terraform module table
  docs/content/indexes/terraform/_index.md
Labels: Needs: Triage :mag:
