Repository Azure/Azure-Verified-Modules, pull requests merged in 2025-04, with the labels that each got.

#1937 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1938 fix: Aligned Bicep PE interface with specs
  docs/static/includes/interfaces/bicep/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/bicep/int.pe.udt.schema2.bicep
Labels: Needs: Triage :mag:, Type: Bug :bug:, Type: Documentation :page_facing_up:

#1939 fix: Removed resource-specific link from zonal schema
  docs/static/includes/interfaces/bicep/int.zone.schema1.bicep
Labels: Type: Documentation :page_facing_up:

#1926 issue template for bicep child modules
  .github/ISSUE_TEMPLATE/1_question_feedback.yml
  .github/ISSUE_TEMPLATE/2_documentation_update.yml
  .github/ISSUE_TEMPLATE/3_module_proposal_avm.yml
  .github/ISSUE_TEMPLATE/4_module_proposal_bicep_child.yml
  .github/ISSUE_TEMPLATE/5_orphaned_module.yml
  docs/content/specs-defs/includes/shared/resource/non-functional/RMNFR1.md
  docs/static/governance/avm-standard-github-labels.csv
Labels: Needs: Triage :mag:

#1943 fix: Update RBAC role assignments to 'Owner' for SPN and UAMI
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/static/scripts/New-AVMBicepBRMForkSetup.ps1
Labels: Needs: Triage :mag:

#1946 Pmeshram/feat/updates main
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
  docs/static/module-indexes/TerraformUtilityModules.csv
Labels: Needs: Triage :mag:

#1947 fix: remove whitespace from TF PTN CSV
  docs/static/module-indexes/TerraformPatternModules.csv
Labels: Type: Bug :bug:, Type: Documentation :page_facing_up:

#1951 feat: document TF test framework
  docs/content/contributing/terraform/testing.md
  docs/hugo.toml
Labels: Language: Terraform :globe_with_meridians:

#1952 fix: tfdocs link in terraform testing
  docs/content/contributing/terraform/testing.md
Labels: Needs: Triage :mag:

#1972 Pmeshram/feat/updates main
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1971 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1973 separate Bicep and TF comms on module proposals
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/static/includes/msg-final-conf-new-orph-mod-owners.md
  docs/static/includes/msg-final-conf-new-prop-mod-owners-bicep.md
  docs/static/includes/msg-final-conf-new-prop-mod-owners-tf.md
Labels: Type: Documentation :page_facing_up:

#1974 fix: Updated description of `defaults` & `waf-aligned` test folders to at most be used as a suffix
  docs/content/specs-defs/includes/bicep/resource/non-functional/BCPRMNFR1.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1953 feat: update changelog spec bcpnrf22
  docs/content/specs-defs/includes/bicep/shared/non-functional/BCPNRF22.md
Labels: Needs: Triage :mag:

#1979 Update int.pe.schema.tf
  docs/static/includes/interfaces/tf/int.pe.schema.tf
Labels: Needs: Triage :mag:

#1984 Pmeshram/feat/updates main
  docs/static/module-indexes/TerraformPatternModules.csv
Labels: Needs: Triage :mag:

#1981 Update Resource and Pattern CSVs
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#1985 update issue triage automation docs for ITA01BCP.1 & ITA01BCP.2 and ITA02BCP.1 & ITA02BCP.2
  docs/content/help-support/issue-triage/issue-triage-automation.md
Labels: Needs: Triage :mag:

#1987 feat: add meta data to repo creation process
  docs/content/contributing/terraform/terraform-contribution-flow/repository-creation-process.md
Labels: Needs: Triage :mag:

#1990 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1998 Pmeshram/feat/updates main
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#2000 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:
