Repository Azure/Azure-Verified-Modules, pull requests merged in 2025-07, with the labels that each got.

#2191 feat: add july 25 community call and fix feb 25 pdf
  docs/content/_index.md
  docs/content/resources/community.md
  docs/static/community/avm-community-call-feb25.pdf
  docs/static/community/avm-community-call-july25.pdf
  docs/static/community/avm-community-call-may24-LAPTOP-A0LOVJ6V-2.pdf
  docs/static/community/avm-community-call-may24-LAPTOP-A0LOVJ6V.pdf
Labels: Type: Documentation :page_facing_up:

#2193 chore: fix csv line endings
  .gitattributes
Labels: Needs: Triage :mag:

#2206 indexes updated
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#2207 feat: update to support `llms.txt` generation
  docs/content/usage/includes/bicep-prerequisites.md
  docs/content/usage/includes/terraform-prerequisites.md
  docs/hugo.toml
  docs/layouts/_default/index.txt
  docs/layouts/_default/list.txt
  docs/layouts/_default/single.txt
Labels: Type: Documentation :page_facing_up:, Type: Feature Request :heavy_plus_sign:

#2218 feat: Adding spec for multi-scope modules
  .github/workflows/platform.updateModuleRegistryTables.yml
  docs/content/specs-defs/includes/bicep/resource/non-functional/BCPRMNFR4.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#2222 Update team RACI description and fix expression in RMNFR1
  docs/content/specs-defs/includes/shared/resource/non-functional/RMNFR1.md
  docs/content/specs-defs/team-definitions.md
Labels: Type: Documentation :page_facing_up:

#2138 feat: add title attribute to tags
  docs/hugo.toml
  docs/layouts/partials/custom-header.html
  docs/static/js/taglist.json
  docs/static/js/tags.js
Labels: Needs: Triage :mag:

#2176 Update terraform.md
  docs/content/usage/solution-development/terraform.md
Labels: Needs: Triage :mag:

#2229 docs: fix path
  docs/content/contributing/terraform/terraform-contribution-flow/repository-creation-process.md
Labels: Needs: Triage :mag:

#2242 Modules indexes update
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
  docs/static/module-indexes/TerraformUtilityModules.csv
Labels: Needs: Triage :mag:
