Repository Azure/Azure-Verified-Modules, pull requests merged in 2025-06, with the labels that each got.

#2106 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/BicepUtilityModules.csv
Labels: Type: Documentation :page_facing_up:

#2107 add PS Summit 2025 recording
  docs/content/resources/_index.md
Labels: Type: Documentation :page_facing_up:

#1942 module deprecation
  .github/ISSUE_TEMPLATE/5_orphaned_module.yml
  .github/ISSUE_TEMPLATE/6_module_deprecation.yml
  docs/content/help-support/issue-triage/avm-issue-triage.md
  docs/content/indexes/_index.md
  docs/content/indexes/bicep/_index.md
  docs/content/indexes/bicep/bicep-pattern-modules.md
  docs/content/indexes/bicep/bicep-resource-modules.md
  docs/content/indexes/bicep/bicep-utility-modules.md
  docs/content/indexes/terraform/_index.md
  docs/content/indexes/terraform/tf-pattern-modules.md
  docs/content/indexes/terraform/tf-resource-modules.md
  docs/content/indexes/terraform/tf-utility-modules.md
  docs/content/resources/_index.md
  docs/content/specs-defs/includes/bicep/shared/non-functional/BCPNFR15.md
  docs/content/specs-defs/module-lifecycle.md
  docs/layouts/partials/countModules.html
  docs/layouts/shortcodes/moduleHistory.html
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/layouts/shortcodes/moduleNameTelemetryGHTeams.html
  docs/layouts/shortcodes/moduleStats.html
  docs/static/governance/avm-standard-github-labels.csv
  docs/static/includes/deprecated-module-notice.md
  docs/static/includes/module-status-legend.md
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/BicepUtilityModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
  docs/static/module-indexes/TerraformUtilityModules.csv
  utilities/pipelines/sharedScripts/teamLinter/Get-AvmCsvData.ps1
Labels: Type: Documentation :page_facing_up:, Type: Hygiene :broom:

#2114 fix bicep utility module counter
  docs/layouts/shortcodes/moduleStats.html
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#2117 May 2025 - TF res module updates
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#2120 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#2128 Fix module index rendering and update specifications
  docs/content/indexes/terraform/tf-pattern-modules.md
  docs/content/indexes/terraform/tf-resource-modules.md
  docs/content/indexes/terraform/tf-utility-modules.md
  docs/content/specs-defs/specs/_index.md
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/layouts/shortcodes/moduleNameTelemetryGHTeams.html
Labels: Type: Documentation :page_facing_up:

#2134 TF updates - SFR3 and contribution guide
  docs/content/contributing/terraform/composition.md
  docs/content/specs-defs/includes/shared/shared/functional/SFR3.md
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#2145 Bicep and TF module index updates (and fixes)
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
  docs/static/module-indexes/TerraformUtilityModules.csv
Labels: Type: Documentation :page_facing_up:

#2155 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#2169 index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#2170 index fixes
  docs/content/indexes/bicep/bicep-pattern-modules.md
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#2154 feat: Updated Bicep Lock Type to allow for custom notes
  docs/static/includes/interfaces/bicep/int.locks.input.bicep
  docs/static/includes/interfaces/bicep/int.locks.udt.schema.bicep
Labels: Needs: Triage :mag:

#2177 showing children without parents in the index
  docs/layouts/shortcodes/moduleHistory.html
  docs/layouts/shortcodes/moduleNameStatusOwners.html
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#2179 fix: Bicep Changelogs - Changes URL to an absolute URL
  docs/content/specs-defs/includes/bicep/shared/non-functional/BCPNFR22.md
Labels: Needs: Triage :mag:

#2186 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:

#2188 fix: SNFR3 spec category update
  docs/content/specs-defs/includes/shared/shared/non-functional/SNFR3.md
Labels: Needs: Triage :mag:
