Repository Azure/Azure-Verified-Modules, pull requests merged in 2025-09, with the labels that each got.

#2296 ai-index-update
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/TerraformPatternModules.csv
Labels: Needs: Triage :mag:

#2302 Bicep resource module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#2311 Change AVM script commands for Windows
  docs/content/contributing/terraform/terraform-contribution-flow/_index.md
  docs/content/contributing/terraform/testing.md
Labels: Needs: Triage :mag:

#2325 Bicep index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#2329 TF modules index updates
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#2334 Bicep module index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/BicepUtilityModules.csv
Labels: Type: Documentation :page_facing_up:

#2336 Terraform indexes update
  docs/static/module-indexes/TerraformPatternModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Needs: Triage :mag:

#2341 docs: remove resolved issue notice from documentation
  docs/content/_index.md
Labels: Needs: Triage :mag:
