Repository Azure/Azure-Verified-Modules, pull requests merged in 2025-01, with the labels that each got.

#1782 module index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Type: Documentation :page_facing_up:

#1773 feat: Bicep contribution guidelines - OIDC setup
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/static/img/bicep-ci/forkSettingsEnvironmentAdd.png
  docs/static/img/bicep-ci/forkSettingsEnvironmentConfigure.png
  docs/static/img/bicep-ci/forkSettingsEnvironmentSecretAdd.png
  docs/static/img/bicep-ci/forkSettingsEnvironmentSecretAdd_02.png
  docs/static/img/bicep-ci/msiOIDCAddFederatedIdentity_01.png
  docs/static/img/bicep-ci/msiOIDCAddFederatedIdentity_02.png
  docs/static/img/bicep-ci/msiOIDCAddFederatedIdentity_03.png
  docs/static/img/bicep-ci/msiOIDCInfo.png
  docs/static/img/bicep-ci/msiOIDCRole.png
  docs/static/scripts/New-AVMBicepBRMForkSetup.ps1
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#1787 updates Private Endpoint interface documentation
  docs/static/includes/interfaces/bicep/int.pe.input1.bicep
  docs/static/includes/interfaces/bicep/int.pe.input2.bicep
  docs/static/includes/interfaces/bicep/int.pe.udt.schema1.bicep
  docs/static/includes/interfaces/bicep/int.pe.udt.schema2.bicep
Labels: Needs: Triage :mag:

#1792 index updates
  docs/static/module-indexes/BicepPatternModules.csv
  docs/static/module-indexes/BicepResourceModules.csv
  docs/static/module-indexes/TerraformResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1797 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Type: Documentation :page_facing_up:

#1738 feat: Added diverse specs for User-defined types
  docs/content/specs-defs/includes/bicep/resource/non-functional/BCPRMNFR2.md
  docs/content/specs-defs/includes/bicep/shared/non-functional/BCPNFR1.md
  docs/content/specs-defs/includes/bicep/shared/non-functional/BCPNFR18.md
  docs/content/specs-defs/includes/bicep/shared/non-functional/BCPNFR19.md
  docs/content/specs-defs/includes/bicep/shared/non-functional/BCPNFR20.md
  docs/content/specs-defs/includes/bicep/shared/non-functional/BCPNFR21.md
  docs/content/specs-defs/includes/bicep/shared/non-functional/BCPNFR9.md
Labels: Type: Documentation :page_facing_up:

#1805 fix: fixes terraform pattern modules catalog
  docs/layouts/shortcodes/moduleNameStatusOwners.html
Labels: Needs: Triage :mag:

#1806 fix: replace test refs and fix edit button
  docs/go.mod
  docs/hugo.toml
Labels: Type: Bug :bug:

#1810 Bicep index updates
  docs/static/module-indexes/BicepPatternModules.csv
Labels: Needs: Triage :mag:

#1809 Update Bicep CI bootstrap tool and docs to support OIDC
  docs/content/contributing/bicep/bicep-contribution-flow/_index.md
  docs/static/scripts/New-AVMBicepBRMForkSetup.ps1
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:, Type: Feature Request :heavy_plus_sign:

#1812 fix: Added tryGet to secretExport interface to address new Bicep warning
  docs/static/includes/interfaces/bicep/int.secExp.udt.schema.bicep
Labels: Type: Documentation :page_facing_up:, Language: Bicep :muscle:

#1814 Bicep module index updates
  docs/static/module-indexes/BicepResourceModules.csv
Labels: Needs: Triage :mag:, Type: Documentation :page_facing_up:

#1815 spelling out Table of Contents
  docs/layouts/partials/topbar/button/toc.html
Labels: Type: Documentation :page_facing_up:
